//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewKnockaboutonline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnockaboutonlineEntities : DbContext
    {
        public KnockaboutonlineEntities()
            : base("name=KnockaboutonlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<COLOR> COLOR { get; set; }
        public virtual DbSet<CONTACT_US> CONTACT_US { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<ORDER> ORDER { get; set; }
        public virtual DbSet<ORDER_DETAIL> ORDER_DETAIL { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<STORAGE> STORAGE { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<SIZE> SIZE { get; set; }
    }
}
